### ISSUE TITLE
Gadget update

### ISSUE THREAD

**Issue by ivanfratric** [theori-io/pwnjs#2]
Hi,

First of all, a very cool project!

Unfortunately, it doesn't work any longer on the newer Chakra versions (testing on Windows 1709 with November patches).

One issue is that some of the gadgets need updating as they can no longer be found.

The more serious issue, however, is that amd64_callfunction now includes
call qword ptr [chakra!_guard_dispatch_icall_fptr]
instead of
call eax
and currently pwnjs relies on the code in amd64_callfunction to load the 3rd and 4th params into r8 and r9. So nopReturn should point to something that is allowed by CFG and immediately returns.

Possibly there are other issues with the newer Chakra version, I haven't tested very thoroughly.

**Comment by ifratric** [comment]
Perhaps this is better replacement for param loading (can load all 4 register params in a single gadget):

https://github.com/Microsoft/ChakraCore/blob/9219195d12be21ac6baa7256ca1bc550f2840fd2/lib/Runtime/Language/amd64/amd64_Thunks.asm#L55

**Comment by ivanfratric** [comment]
Perhaps this is better replacement for param loading (can load all 4 register params in a single gadget):

https://github.com/Microsoft/ChakraCore/blob/9219195d12be21ac6baa7256ca1bc550f2840fd2/lib/Runtime/Language/amd64/amd64_Thunks.asm#L55

**Comment by ivanfratric** [comment]
Correction, the Windows version I was testing on is 1709 (Fall Creators Update) and not 1607 as I wrote initially (edited now).

**Comment by awesie** [comment]
Thanks! I'll look into it this weekend. If you have any more fixes or suggestions, don't hesitate to send them. 👍
